### ISSUE TITLE
Pull Request Deployment

### ISSUE THREAD

**Issue by webard** [mehrancodes/veyoze#51]
Hello,

When using veyoze (my CI is named "Deploy provision", i think "deploy" word in name cause this), in my project's Pull Request show information

<img width="940" alt="image" src="https://github.com/mehrancodes/veyoze/assets/855788/02c9051a-cbc1-4322-97e0-deba4df396cc">

Is there any chance to put information about deployment (probably preview link) to this section, instead of pull request comment? 

Unfortunately I didn't found a way to do this, only some informations: https://sanderknape.com/2020/05/deploy-pull-requests-github-actions-deployments/

**Comment by mehrancodes** [comment]
I like this idea! Definitely gonna try it this weekend.

**Comment by mehrancodes** [comment]
It has been a while since I tried GitHub Deployments, and while it gives us a nice way to get the environment URL, I discovered that I am unable to add any extra information such as the database URL (which I have added recently to the PR comments feature). 

In the future, we hope to improve the PR comments even more, so QA engineers have access to a variety of links all in one place. 

In any case, thank you for your recommendation and please do not hesitate to contact us again whenever you have another idea in mind.
