### ISSUE TITLE
Veyoze converts "+" in env keys to " "

### ISSUE THREAD

**Issue by gbradley** [mehrancodes/veyoze#57]
I'm storing my ENV variables in a GitHub secret and referencing them via `FORGE_ENV_KEYS`. I noticed one of my base64 encoded strings has had its `+` characters replaced with a space ` `:

Original:

`MY_SECRET="base64:B5+B6voa8tXtkUtkvb+VaV8sd2nvu9y80QmTnJ5CveQ="`

Results in

`MY_SECRET="base64:B5 B6voa8tXtkUtkvb VaV8sd2nvu9y80QmTnJ5CveQ="`

Afaik a + character is valid within base64 encoding.

**Comment by mehrancodes** [comment]
Interesting. Looks like the issue comes from the [parse_str method I've used](https://github.com/mehrancodes/veyoze/blob/516463e97314c9bbe33d29c6601b5786b922b673/app/Actions/TextToArray.php#L31) to convert a string variable to array.

It's on my list to check out. Thank you for investing time in Veyoze!

**Comment by gbradley** [comment]
Thanks! I wasn't sure if this was going to be a Veyoze / Forge SDK issue, did have a quick look around but didn't notice that method call.

Spent some time getting it up and running on a client server today, works really well so far!

**Comment by mehrancodes** [comment]
Found a quick but secure solution ✅. I'll make a PR once I got added some test assertions.

**Comment by mehrancodes** [comment]
Addressed this issue in this release: https://github.com/mehrancodes/veyoze/releases/tag/v0.1.6

Feel free to drop a comment if you still run into any problems with it.
